jQuery.jqconsole = function(arg1, arg2, arg3, arg4) {}
var JQConsole = {};
JQConsole.Write = function(arg1, arg2, arg3) {}
JQConsole.Focus = function() {}
JQConsole.Prompt = function(arg1, arg2) {}
JQConsole.Prompt = function(arg1, arg2, arg3) {}
JQConsole.Prompt = function(arg1, arg2, arg3, arg4) {}
JQConsole.GetPromptText = function() {}
JQConsole.SetPromptText = function(arg1) {}
JQConsole.RegisterMatching = function(arg1, arg2, arg3) {}
JQConsole.RegisterShortcut = function(arg1, arg2) {}
