#!/bin/sh

# fetch submodules
#git submodule init

# get some files to the public dir
#wget -O resources/public/js/jquery-2.0.3.min.js http://code.jquery.com/jquery-2.0.3.min.js
#wget -O resources/public/js/jquery-migrate-1.2.1.min.js http://code.jquery.com/jquery-migrate-1.2.1.min.js
#cp lib/jq-console/jqconsole.min.js resources/public/js

# bootstrap cljs compiler
cd script
sed "s/closure\-compiler\.googlecode\.com\/files/dl\.google\.com\/closure-compiler/" bootstrap > bootstrap

cd ..
./script/bootstrap
./script/compile
